name: 'Looker Janitor'
description: Clean and organize Looker lookml view.lkml files.
author: 'Alhan Keser'

runs:
  using: 'ubuntu-latest'
  main: 'main.py'

branding:
  icon: check-square
  color: green
