name: Tests
on:
    pull_request:
      types:  [opened, synchronize]
    push:
      branches:
        - main

jobs:
    run-tests:
        permissions:
          contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Configure Git user
              run : |
                git config user.name github-actions
                git config user.email github-actions@github.com
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            # - name: setup_test_order_field_types
            #   shell: bash
            #   run: |
            #     cp looker-janitor/tests/test_files/test_order_field_types/input.view.lkml looker-janitor/tests/test_files/test_order_field_types/output.view.lkml
            # - name: test_order_field_types
            #   id: test_order_field_types
            #   uses: alhankeser/looker-janitor-action@dev
            #   with:
            #     files: |
            #       looker-janitor/tests/test_files/test_order_field_types/output.view.lkml
            # - name: check_test_order_field_types
            #   id: check_test_order_field_types
            #   shell: bash
            #   run: |
            #     if diff -s "looker-janitor/tests/test_files/test_order_field_types/output.view.lkml" "looker-janitor/tests/test_files/test_order_field_types/expected.view.lkml"; then
            #       files_match=true
            #     else
            #       files_match=false
            #     fi
            #     echo "result=$files_match" >> $GITHUB_OUTPUT
            # - name: print results
            #   shell: bash
            #   run: |
            #     echo ${{ steps.check_test_order_field_types.outputs.result }}
            - name: Setup test_type_order_param
              shell: bash
              run: |
                cp tests/test_files/test_type_order_param/input.view.lkml tests/test_files/test_type_order_param/output.view.lkml
            - name: Run test_type_order_param
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_type_order_param/output.view.lkml
                type_order: |
                  measure
                  dimension
            - name: Compare output to expected
              id: test_type_order_param
              shell: bash
              run: |
                if diff -s "tests/test_files/test_type_order_param/output.view.lkml" "tests/test_files/test_type_order_param/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_type_order_param.outputs.result }}
            - name: Setup test_param_order
              shell: bash
              run: |
                cp tests/test_files/test_param_order/input.view.lkml tests/test_files/test_param_order/output.view.lkml
            - name: Run test_param_order
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_param_order/output.view.lkml
            - name: Compare output to expected
              id: test_param_order
              shell: bash
              run: |
                if diff -s "tests/test_files/test_param_order/output.view.lkml" "tests/test_files/test_param_order/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_param_order.outputs.result }}
            - name: Setup test_param_order_param
              shell: bash
              run: |
                cp tests/test_files/test_param_order_param/input.view.lkml tests/test_files/test_param_order_param/output.view.lkml
            - name: Run test_param_order_param
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_param_order_param/output.view.lkml
                param_order: |
                  sql
                  type
            - name: Compare output to expected
              id: test_param_order_param
              shell: bash
              run: |
                if diff -s "tests/test_files/test_param_order_param/output.view.lkml" "tests/test_files/test_param_order_param/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_param_order_param.outputs.result }}
            - name: Setup test_primary_key_first
              shell: bash
              run: |
                cp tests/test_files/test_primary_key_first/input.view.lkml tests/test_files/test_primary_key_first/output.view.lkml
            - name: Run test_primary_key_first
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_primary_key_first/output.view.lkml
            - name: Compare output to expected
              id: test_primary_key_first
              shell: bash
              run: |
                if diff -s "tests/test_files/test_primary_key_first/output.view.lkml" "tests/test_files/test_primary_key_first/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_primary_key_first.outputs.result }}
            - name: Setup test_primary_key_first_param
              shell: bash
              run: |
                cp tests/test_files/test_primary_key_first_param/input.view.lkml tests/test_files/test_primary_key_first_param/output.view.lkml
            - name: Run test_primary_key_first_param
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_primary_key_first_param/output.view.lkml
                primary_key_first: |
                  false
            - name: Compare output to expected
              id: test_primary_key_first_param
              shell: bash
              run: |
                if diff -s "tests/test_files/test_primary_key_first_param/output.view.lkml" "tests/test_files/test_primary_key_first_param/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_primary_key_first_param.outputs.result }}
            - name: Setup test_order_fields
              shell: bash
              run: |
                cp tests/test_files/test_order_fields/input.view.lkml tests/test_files/test_order_fields/output.view.lkml
            - name: Run test_order_fields
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_order_fields/output.view.lkml
            - name: Compare output to expected
              id: test_order_fields
              shell: bash
              run: |
                if diff -s "tests/test_files/test_order_fields/output.view.lkml" "tests/test_files/test_order_fields/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_order_fields.outputs.result }}
            - name: Setup test_order_fields_param
              shell: bash
              run: |
                cp tests/test_files/test_order_fields_param/input.view.lkml tests/test_files/test_order_fields_param/output.view.lkml
            - name: Run test_order_fields_param
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_order_fields_param/output.view.lkml
                order_fields: |
                  false
            - name: Compare output to expected
              id: test_order_fields_param
              shell: bash
              run: |
                if diff -s "tests/test_files/test_order_fields_param/output.view.lkml" "tests/test_files/test_order_fields_param/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_order_fields_param.outputs.result }}
            - name: Setup test_order_by_label
              shell: bash
              run: |
                cp tests/test_files/test_order_by_label/input.view.lkml tests/test_files/test_order_by_label/output.view.lkml
            - name: Run test_order_by_label
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_order_by_label/output.view.lkml
            - name: Compare output to expected
              id: test_order_by_label
              shell: bash
              run: |
                if diff -s "tests/test_files/test_order_by_label/output.view.lkml" "tests/test_files/test_order_by_label/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_order_by_label.outputs.result }}
            - name: Setup test_order_by_label_param
              shell: bash
              run: |
                cp tests/test_files/test_order_by_label_param/input.view.lkml tests/test_files/test_order_by_label_param/output.view.lkml
            - name: Run test_order_by_label_param
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_order_by_label_param/output.view.lkml
                order_fields_by_label: |
                  false
            - name: Compare output to expected
              id: test_order_by_label_param
              shell: bash
              run: |
                if diff -s "tests/test_files/test_order_by_label_param/output.view.lkml" "tests/test_files/test_order_by_label_param/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_order_by_label_param.outputs.result }}
            - name: Setup test_localization_file_path_param
              shell: bash
              run: |
                cp tests/test_files/test_localization_file_path_param/input.view.lkml tests/test_files/test_localization_file_path_param/output.view.lkml
            - name: Run test_localization_file_path_param
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_localization_file_path_param/output.view.lkml
                localization_file_path: |
                  tests/test_files/test_localization_file_path_param/en.strings.json
            - name: Compare output to expected
              id: test_localization_file_path_param
              shell: bash
              run: |
                if diff -s "tests/test_files/test_localization_file_path_param/output.view.lkml" "tests/test_files/test_localization_file_path_param/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_localization_file_path_param.outputs.result }}
            - name: Setup test_order_field_parameters_param
              shell: bash
              run: |
                cp tests/test_files/test_order_field_parameters_param/input.view.lkml tests/test_files/test_order_field_parameters_param/output.view.lkml
            - name: Run test_order_field_parameters_param
              uses: alhankeser/looker-janitor-action@latest
              with:
                files: |
                  tests/test_files/test_order_field_parameters_param/output.view.lkml
                order_field_parameters: |
                  false
            - name: Compare output to expected
              id: test_order_field_parameters_param
              shell: bash
              run: |
                if diff -s "tests/test_files/test_order_field_parameters_param/output.view.lkml" "tests/test_files/test_order_field_parameters_param/expected.view.lkml"; then
                  files_match=true
                else
                  files_match=false
                fi
                echo "result=$files_match" >> $GITHUB_OUTPUT
            - name: Print Results
              shell: bash
              run: |
                echo ${{ steps.test_order_field_parameters_param.outputs.result }}